# Generated by Django 3.2.9 on 2021-11-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('price', models.PositiveIntegerField()),
                ('measure_unit', models.CharField(max_length=10)),
                ('supplier_name', models.CharField(max_length=64)),
            ],
        ),
    ]
