# Generated by Django 3.1.7 on 2021-11-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='наименование раздела')),
            ],
            options={
                'verbose_name': 'раздел каталога',
                'verbose_name_plural': 'разделы каталога',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date',
            field=models.DateField(auto_now_add=True, verbose_name='дата поступления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measure_unit',
            field=models.CharField(max_length=10, verbose_name='единицы измерения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier_name',
            field=models.CharField(max_length=64, verbose_name='имя поставщика'),
        ),
        migrations.AddField(
            model_name='product',
            name='catalog_section',
            field=models.ManyToManyField(to='catalog.CatalogSection', verbose_name='раздел каталога'),
        ),
    ]
