# Generated by Django 3.1.7 on 2021-11-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20211128_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catalog_section',
            new_name='catalog_sections',
        ),
    ]
