# Generated by Django 3.1.7 on 2021-11-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20211128_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catalog_sections',
            field=models.ManyToManyField(related_name='catalog_sections', to='catalog.CatalogSection', verbose_name='раздел каталога'),
        ),
    ]
