# Generated by Django 3.1.7 on 2021-11-28 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('catalog', '0005_product_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogsection',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='site',
        ),
        migrations.AddField(
            model_name='product',
            name='site',
            field=models.ManyToManyField(to='sites.Site'),
        ),
    ]
